---
# tasks file for virtualbox: ubuntu.yml
- name: add virtualbox oracle apt key
  sudo: yes
  apt_key: url="{{ virtualbox_key_url }}" state=present
  tags: virtualbox

- name: add virtualbox repository
  sudo: yes
  apt_repository: repo="{{ virtualbox_repo }}" state=present
  tags: virtualbox

- name: install virtualbox
  sudo: yes
  apt: name="{{ virtualbox_pkg_name }}" state=present update_cache=yes
  tags: virtualbox

- name: install virtualbox dkms package
  sudo: yes
  apt: name="{{ virtualbox_dkms_pkg_name }}" state=present
  when: virtualbox_install_dkms
  tags: virtualbox_dkms
